In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print("Vectorization: "+str((toc-tic)*1000)+"ms")

Vectorization: 1.207113265991211ms


In [6]:
c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("For loop: "+str((toc-tic)*1000)+"ms")

For loop: 581.8850994110107ms


In [8]:
A = np.array([[5, 0, 4, 6],
            [1, 1, 5, 8],
            [1, 3, 9, 9]])
print(A)

[[5 0 4 6]
 [1 1 5 8]
 [1 3 9 9]]


In [9]:
cal = A.sum(axis=0)
print(cal)

[ 7  4 18 23]


In [10]:
perc = 100*A/cal.reshape(1, 4)
print(perc)

[[71.42857143  0.         22.22222222 26.08695652]
 [14.28571429 25.         27.77777778 34.7826087 ]
 [14.28571429 75.         50.         39.13043478]]
