In [1]:
from __future__ import print_function
import torch
import torchvision

## 张量

In [5]:
# 未初始化
x = torch.empty(5, 3)
print(x)

# 随机初始化
x = torch.rand(5, 3)
print(x)

# 0初始化
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# 给定数据创建张量
x = torch.tensor([[1,1],[2,2]])
print(x)

# 从已有的张量创建张量
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

print(x.size())

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.6136, 0.1158, 0.6799],
        [0.9316, 0.6019, 0.2764],
        [0.6095, 0.8856, 0.6233],
        [0.9068, 0.7389, 0.4268],
        [0.8680, 0.0348, 0.0028]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1],
        [2, 2]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1777,  0.8893, -0.4335],
        [-1.3371, -1.4099,  0.7527],
        [-0.8562,  1.7667,  1.0009],
        [ 1.6526,  1.0280,  0.4585],
        [-0.5309, -0.9224, -0.7697]])
torch.Size([5, 3])


## 基本运算

In [7]:
y = torch.rand(5, 3)
print(x+y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# 后缀_的运算，基本上都表示对调用方直接进行更改
y.add_(x)
print(y)

tensor([[-0.2641,  0.9867, -0.2788],
        [-0.4667, -0.6177,  1.0333],
        [-0.2591,  2.0931,  1.5914],
        [ 2.1619,  1.1920,  0.9952],
        [ 0.0812, -0.2362, -0.3309]])
tensor([[-0.2641,  0.9867, -0.2788],
        [-0.4667, -0.6177,  1.0333],
        [-0.2591,  2.0931,  1.5914],
        [ 2.1619,  1.1920,  0.9952],
        [ 0.0812, -0.2362, -0.3309]])
tensor([[-0.2641,  0.9867, -0.2788],
        [-0.4667, -0.6177,  1.0333],
        [-0.2591,  2.0931,  1.5914],
        [ 2.1619,  1.1920,  0.9952],
        [ 0.0812, -0.2362, -0.3309]])
tensor([[-0.2641,  0.9867, -0.2788],
        [-0.4667, -0.6177,  1.0333],
        [-0.2591,  2.0931,  1.5914],
        [ 2.1619,  1.1920,  0.9952],
        [ 0.0812, -0.2362, -0.3309]])


In [9]:
# 和np类似，表示x索引为1的一列
print(x[:, 1])

# view用于改变形状，-1表示推导出的默认值
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

tensor([ 0.8893, -1.4099,  1.7667,  1.0280, -0.9224])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
x = torch.randn(1)
val = x.item()
print(val)

1.4854084253311157


## Numpy 转换

In [13]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [15]:
# 当有CUDA时
if torch.cuda.is_available():
    device = torch.device("cuda")
    # 直接在gpu建立张量y
    y = torch.ones_like(x, device=device)
    # 或者调用to()方法，改变存储位置
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

## autograd

In [16]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x+2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(z, out)

print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
None


In [17]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [18]:
out.backward()

print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [19]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-649.4747,  770.5900,   12.3116], grad_fn=<MulBackward0>)


In [20]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [21]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [22]:
print(x.requires_grad)

y = x.detach()
print(y.requires_grad)

print(x.eq(y).all())

True
False
tensor(True)
